/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import { SidebarRow3Props } from 'types';

 
const Property1Default: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  width: "100%",  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `8px 6px`,  
  boxSizing: `border-box`,  
  height: `54.66px`,  
});
  
const ImgIcon: any = styled("img")({  
  height: `19.66px`,  
  width: `17.69px`,  
  margin: `0px`,  
});
  
const Text: any = styled("div")(({ theme }: any) =>({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: theme.palette["Text"]["Secondary"],  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `600`,  
  fontSize: `12px`,  
  letterSpacing: `0.48px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  margin: `4px 0px 0px 0px`,  
}));
 
function SidebarRow3(props: SidebarRow3Props): JSX.Element {
  
  return (
    <Property1Default  className={props.className}   >
      <ImgIcon  src={`assets/images/sidebarrow3_img_icon.png`} alt={"img:icon"}/>
      <Text >
        {`Dashboard`}
          </Text>
    </Property1Default>
  );
}

export default SidebarRow3;
