/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import SidebarRow1 from 'components/SidebarRow1/SidebarRow1';
import { Sidebar1Props } from 'types';

 
const CollapsableOpen: any = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  height: `700px`,  
  width: "100%",  
  justifyContent: `space-between`,  
  alignItems: `flex-start`,  
  padding: `16px`,  
  boxSizing: `border-box`,  
});
  
const Top: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `20px 0px 0px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  height: `482.5px`,  
  width: `258px`,  
});
  
const Logo: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px 0px 0px 40px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
  width: `168px`,  
});
  
const MoonbaseLogo: any = styled("img")({  
  height: `14.22px`,  
  width: `128px`,  
  objectFit: `contain`,  
  margin: `0px`,  
});
  
const MoonbaseLogoM: any = styled("img")({  
  height: `11px`,  
  width: `9px`,  
  objectFit: `cover`,  
  margin: `0px`,  
});
  
const List: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `56px 0px 0px 0px`,  
  width: `258px`,  
});
  
const SidebarRow11: any = styled(SidebarRow1)(({ theme }: any) =>({  
  alignSelf: `stretch`,  
  height: `40px`,  
  margin: `0px`,  
}));
  
const SidebarRow12: any = styled(SidebarRow1)(({ theme }: any) =>({  
  alignSelf: `stretch`,  
  height: `40px`,  
  margin: `10px 0px 0px 0px`,  
}));
  
const SidebarRow13: any = styled(SidebarRow1)(({ theme }: any) =>({  
  alignSelf: `stretch`,  
  height: `40px`,  
  margin: `10px 0px 0px 0px`,  
}));
  
const SidebarRow14: any = styled(SidebarRow1)(({ theme }: any) =>({  
  alignSelf: `stretch`,  
  height: `40px`,  
  margin: `10px 0px 0px 0px`,  
}));
  
const SidebarRow15: any = styled(SidebarRow1)(({ theme }: any) =>({  
  alignSelf: `stretch`,  
  height: `40px`,  
  margin: `10px 0px 0px 0px`,  
}));
  
const SidebarRow16: any = styled(SidebarRow1)(({ theme }: any) =>({  
  alignSelf: `stretch`,  
  height: `40px`,  
  margin: `10px 0px 0px 0px`,  
}));
  
const SidebarRow17: any = styled(SidebarRow1)(({ theme }: any) =>({  
  alignSelf: `stretch`,  
  height: `40px`,  
  margin: `10px 0px 0px 0px`,  
}));
  
const SidebarRow18: any = styled(SidebarRow1)(({ theme }: any) =>({  
  alignSelf: `stretch`,  
  height: `40px`,  
  margin: `10px 0px 0px 0px`,  
}));
  
const Account: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  width: `258px`,  
});
  
const Divide: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `10px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
  width: `258px`,  
});
  
const DividerHorizontal: any = styled("div")({  
  border: `1px solid theme.customShadows["Light"]["Other"]["Divider"].color`,  
  boxSizing: `border-box`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  alignSelf: `stretch`,  
  height: `1px`,  
  margin: `0px`,  
  width: `258px`,  
});
  
const Btm: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px 30px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `8px 0px 0px 0px`,  
  width: `258px`,  
});
  
const Avatar1: any = styled("img")({  
  height: `32px`,  
  width: `32px`,  
  objectFit: `cover`,  
  margin: `0px`,  
});
  
const EllenCho: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(53, 53, 53, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `500`,  
  fontSize: `16px`,  
  letterSpacing: `0.64px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  flexGrow: `1`,  
  margin: `0px 0px 0px 8px`,  
});
 
function Sidebar1(props: Sidebar1Props): JSX.Element {
  
  return (
    <CollapsableOpen  className={props.className}   >
      <Top >
        <Logo >
          <MoonbaseLogo  src={`assets/images/Sidebar1_MoonbaseLogo.png`} alt={"MoonbaseLogo"}/>
          {false &&
            <MoonbaseLogoM  src={`assets/images/Sidebar1_MoonbaseLogo_M.png`} alt={"MoonbaseLogo_M"}/>
          }
        </Logo>
        <List >
          <SidebarRow11   />
          <SidebarRow12   />
          <SidebarRow13   />
          <SidebarRow14   />
          <SidebarRow15   />
          <SidebarRow16   />
          <SidebarRow17   />
          <SidebarRow18   />
        </List>
      </Top>
      <Account >
        <Divide >
          <DividerHorizontal >
          </DividerHorizontal>
        </Divide>
        <Btm >
          <Avatar1  src={`assets/images/Sidebar1_Avatar.png`} alt={"Avatar"}/>
          <EllenCho >
            {`Ellen Cho`}
              </EllenCho>
        </Btm>
      </Account>
    </CollapsableOpen>
  );
}

export default Sidebar1;
