/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import { Button } from '@mui/material';
import { styled } from '@mui/material/styles';
import Sidebar2 from 'components/Sidebar2/Sidebar2';
import { Dashboard3Props } from 'types';

 
const TypeQuestSidebarOpen: any = styled("div")({  
  backgroundColor: `rgba(24, 24, 24, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  width: "100%",  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  height: `1024px`,  
});
  
const Page: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  height: `1024px`,  
  margin: `0px`,  
  width: `1423px`,  
});
  
const Sidebar21: any = styled(Sidebar2)(({ theme }: any) =>({  
  alignSelf: `stretch`,  
  width: `290px`,  
  margin: `0px`,  
}));
  
const Content: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  flexGrow: `1`,  
  margin: `0px`,  
  width: `1133px`,  
});
  
const Nav: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  height: `80px`,  
  margin: `0px`,  
  width: `1133px`,  
});
  
const Content1: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  height: `80px`,  
  margin: `0px`,  
  width: `1133px`,  
});
  
const Frame6: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-end`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
  width: `1133px`,  
});
  
const RightSide2: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-end`,  
  alignItems: `center`,  
  padding: `0px 28px 0px 0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
  width: `381.44px`,  
});
  
const Frame5: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
  width: `353.44px`,  
});
  
const Calendar: any = styled("img")({  
  height: `25.83px`,  
  width: `22.5px`,  
  margin: `0px`,  
});
  
const Divider: any = styled("img")({  
  height: `23.96px`,  
  width: `2px`,  
  margin: `0px 0px 0px 40px`,  
});
  
const AndrewSmith: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `700`,  
  fontSize: `16px`,  
  letterSpacing: `0.64px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  width: `127px`,  
  height: `25.83px`,  
  margin: `0px 0px 0px 40px`,  
});
  
const User: any = styled("img")({  
  height: `22.5px`,  
  width: `20px`,  
  margin: `0px 0px 0px 40px`,  
});
  
const Rectangle9: any = styled("img")({  
  height: `10.97px`,  
  width: `21.94px`,  
  margin: `0px 0px 0px 40px`,  
});
  
const Sec1: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `30px 60px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  height: `400px`,  
  margin: `0px`,  
  overflow: `hidden`,  
  width: `1133px`,  
});
  
const Hero: any = styled("div")({  
  border: `1px solid rgba(176, 176, 176, 1)`,  
  boxSizing: `border-box`,  
  borderRadius: `8px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `18px 78px`,  
  alignSelf: `stretch`,  
  height: `306px`,  
  margin: `0px`,  
  width: `1013px`,  
});
  
const HeroContent: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
  width: `857px`,  
});
  
const Text: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
  margin: `0px`,  
  width: `398px`,  
});
  
const WelcomeToMoonBaseAnd: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `600`,  
  fontSize: `28px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  margin: `0px`,  
});
  
const CongratsOnYour1StDay: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(132, 132, 132, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `600`,  
  fontSize: `17px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `28px`,  
  textTransform: `none`,  
  margin: `10px 0px 0px 0px`,  
});
  
const UndrawPartyingReAt7F: any = styled("img")({  
  height: `270px`,  
  width: `342px`,  
  margin: `0px 0px 0px 117px`,  
});
  
const Sec2: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 61px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
  width: `1133px`,  
});
  
const Upcoming: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 240px 0px 0px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
  margin: `0px`,  
  width: `663px`,  
});
  
const Upcoming1: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `600`,  
  fontSize: `22px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  margin: `0px`,  
});
  
const Event1: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `22px 0px 0px 0px`,  
  width: `423px`,  
});
  
const Frame42: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
  width: `231px`,  
});
  
const Today: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(159, 159, 159, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `700`,  
  fontSize: `17px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `28px`,  
  textTransform: `none`,  
  margin: `0px`,  
});
  
const YourFirstDayAtMoonBa: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `600`,  
  fontSize: `17px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `28px`,  
  textTransform: `none`,  
  margin: `0px`,  
});
  
const Rectangle10: any = styled("div")({  
  backgroundColor: `rgba(218, 218, 218, 1)`,  
  alignSelf: `stretch`,  
  height: `2px`,  
  margin: `15px 0px 0px 0px`,  
  width: `423px`,  
});
  
const Event2: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `22px 0px 0px 0px`,  
  width: `423px`,  
});
  
const Frame41: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
  width: `287px`,  
});
  
const Friday: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(159, 159, 159, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `700`,  
  fontSize: `17px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `28px`,  
  textTransform: `none`,  
  margin: `0px`,  
});
  
const Setup1StWorkspacePro: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `600`,  
  fontSize: `17px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `28px`,  
  textTransform: `none`,  
  margin: `0px`,  
});
  
const Rectangle11: any = styled("div")({  
  backgroundColor: `rgba(218, 218, 218, 1)`,  
  alignSelf: `stretch`,  
  height: `2px`,  
  margin: `15px 0px 0px 0px`,  
  width: `423px`,  
});
  
const Link1: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `22px 0px 0px 0px`,  
  width: `283.5px`,  
});
  
const Vector: any = styled("img")({  
  height: `22.5px`,  
  width: `19.5px`,  
  margin: `0px`,  
});
  
const AddReminderToYourCal: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(77, 165, 252, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `700`,  
  fontSize: `17px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `28px`,  
  textTransform: `none`,  
  margin: `0px 0px 0px 11px`,  
});
  
const RightSide: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
  width: `348px`,  
});
  
const ButtonContained: any = styled(Button)({  
  margin: `0px`,  
});
  
const QuickAccess: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `41px 0px 0px 0px`,  
  width: `348px`,  
});
  
const QuickAccess1: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `600`,  
  fontSize: `22px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  margin: `0px`,  
});
  
const Box: any = styled("div")({  
  border: `1px solid rgba(176, 176, 176, 1)`,  
  boxSizing: `border-box`,  
  borderRadius: `4px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `24px`,  
  width: `348px`,  
  margin: `24px 0px 0px 0px`,  
});
  
const YouHave3ProjectNotif: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `600`,  
  fontSize: `20px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `28px`,  
  textTransform: `none`,  
  margin: `0px`,  
});
  
const SeeYourNotifications: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(77, 165, 252, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `700`,  
  fontSize: `17px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `28px`,  
  textTransform: `none`,  
  margin: `7px 0px 0px 0px`,  
});
 
function Dashboard3(props: Dashboard3Props): JSX.Element {
  
  return (
    <TypeQuestSidebarOpen  className={props.className}   >
      <Page >
        <Sidebar21   />
        <Content >
          <Nav >
            <Content1 >
              <Frame6 >
                <RightSide2 >
                  <Frame5 >
                    <Calendar  src={`assets/images/Dashboard3_calendar.png`} alt={"calendar"}/>
                    <Divider  src={`assets/images/Dashboard3_divider.png`} alt={"divider"}/>
                    <AndrewSmith >
                      {`Andrew Smith`}
                        </AndrewSmith>
                    <User  src={`assets/images/Dashboard3_user.png`} alt={"user"}/>
                    <Rectangle9  src={`assets/images/Dashboard3_Rectangle_9.png`} alt={"Rectangle 9"}/>
                  </Frame5>
                </RightSide2>
              </Frame6>
            </Content1>
          </Nav>
          <Sec1 >
            <Hero >
              <HeroContent >
                <Text >
                  <WelcomeToMoonBaseAnd >
                    {`Welcome to Moon Base, Andrew`}
                      </WelcomeToMoonBaseAnd>
                  <CongratsOnYour1StDay >
                    {`Congrats on your 1st day on the team!`}
                      </CongratsOnYour1StDay>
                </Text>
                <UndrawPartyingReAt7F  src={`assets/images/Dashboard3_undraw_partying_re_at7f_1.png`} alt={"undraw_partying_re_at7f 1"}/>
              </HeroContent>
            </Hero>
          </Sec1>
          <Sec2 >
            <Upcoming >
              <Upcoming1 >
                {`Upcoming`}
                  </Upcoming1>
              <Event1 >
                <Frame42 >
                  <Today >
                    {`Today`}
                      </Today>
                  <YourFirstDayAtMoonBa >
                    {`Your First Day at Moon Base`}
                      </YourFirstDayAtMoonBa>
                </Frame42>
                <Rectangle10 >
                </Rectangle10>
              </Event1>
              <Event2 >
                <Frame41 >
                  <Friday >
                    {`Friday`}
                      </Friday>
                  <Setup1StWorkspacePro >
                    {`“Setup 1st Workspace” Project Due`}
                      </Setup1StWorkspacePro>
                </Frame41>
                <Rectangle11 >
                </Rectangle11>
              </Event2>
              <Link1 >
                <Vector  src={`assets/images/Dashboard3_Vector.png`} alt={"Vector"}/>
                <AddReminderToYourCal >
                  {`Add reminder to your calendar`}
                    </AddReminderToYourCal>
              </Link1>
            </Upcoming>
            <RightSide >
              <ButtonContained variant="contained" size="large" color="primary"    > Begin Onboarding </ButtonContained>
              <QuickAccess >
                <QuickAccess1 >
                  {`Quick access`}
                    </QuickAccess1>
                <Box >
                  <YouHave3ProjectNotif >
                    {`You have 3 Project 
Notifications`}
                      </YouHave3ProjectNotif>
                  <SeeYourNotifications >
                    {`See your notifications >`}
                      </SeeYourNotifications>
                </Box>
              </QuickAccess>
            </RightSide>
          </Sec2>
        </Content>
      </Page>
    </TypeQuestSidebarOpen>
  );
}

export default Dashboard3;
