/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import SidebarRow2 from 'components/SidebarRow2/SidebarRow2';
import { Sidebar2Props } from 'types';
import useSidebar2 from 'components/Sidebar2/useSidebar2';
 
const CollapsableOpen: any = styled("div")({  
  backgroundColor: `rgba(0, 0, 0, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  height: `700px`,  
  width: "100%",  
  justifyContent: `space-between`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
});
  
const Top: any = styled("div", {
    shouldForwardProp: prop => !["data"].includes(prop.toString())
    })(({ data }: any) =>({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `20px 0px 0px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  width: data.algo=1 ? `90px` : `290px`,  
}));
  
const Logo: any = styled("div", {
    shouldForwardProp: prop => !["data"].includes(prop.toString())
    })(({ data }: any) =>({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: data.algo=1 ? `16px 0px 0px 43px` : `16px 0px 0px 40px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
  width: data.algo=1 ? `52px` : `148px`,  
}));
  
const MoonbaseLogo: any = styled("img")({  
  height: `12px`,  
  width: `108px`,  
  objectFit: `cover`,  
  margin: `0px`,  
});
  
const MoonbaseLogoM: any = styled("img")({  
  height: `11px`,  
  width: `9px`,  
  objectFit: `cover`,  
  margin: `0px`,  
});
  
const List: any = styled("div", {
    shouldForwardProp: prop => !["data"].includes(prop.toString())
    })(({ data }: any) =>({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 0px 0px 19px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `56px 0px 0px 0px`,  
  width: data.algo=1 ? `90px` : `290px`,  
}));
  
const SidebarRow21: any = styled(SidebarRow2)(({ theme }: any) =>({  
  alignSelf: `stretch`,  
  height: `40px`,  
  margin: `0px`,  
}));
  
const SidebarRow22: any = styled(SidebarRow2)(({ theme }: any) =>({  
  alignSelf: `stretch`,  
  height: `40px`,  
  margin: `6px 0px 0px 0px`,  
}));
  
const SidebarRow23: any = styled(SidebarRow2)(({ theme }: any) =>({  
  alignSelf: `stretch`,  
  height: `40px`,  
  margin: `6px 0px 0px 0px`,  
}));
  
const SidebarRow24: any = styled(SidebarRow2)(({ theme }: any) =>({  
  alignSelf: `stretch`,  
  height: `40px`,  
  margin: `6px 0px 0px 0px`,  
}));
  
const SidebarRow25: any = styled(SidebarRow2)(({ theme }: any) =>({  
  alignSelf: `stretch`,  
  height: `40px`,  
  margin: `6px 0px 0px 0px`,  
}));
  
const SidebarRow26: any = styled(SidebarRow2)(({ theme }: any) =>({  
  alignSelf: `stretch`,  
  height: `40px`,  
  margin: `6px 0px 0px 0px`,  
}));
  
const SidebarRow27: any = styled(SidebarRow2)(({ theme }: any) =>({  
  alignSelf: `stretch`,  
  height: `40px`,  
  margin: `6px 0px 0px 0px`,  
}));
  
const SidebarRow28: any = styled(SidebarRow2)(({ theme }: any) =>({  
  alignSelf: `stretch`,  
  height: `40px`,  
  margin: `6px 0px 0px 0px`,  
}));
  
const Account: any = styled("div", {
    shouldForwardProp: prop => !["data"].includes(prop.toString())
    })(({ data }: any) =>({  
  backgroundColor: `rgba(43, 43, 43, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  height: `60px`,  
  width: data.algo=1 ? `90px` : `290px`,  
}));
  
const Frame1: any = styled("div", {
    shouldForwardProp: prop => !["data"].includes(prop.toString())
    })(({ data }: any) =>({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px 30px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
  width: data.algo=1 ? `90px` : `290px`,  
}));
  
const Avatar1: any = styled("img")({  
  height: `32px`,  
  width: `32px`,  
  objectFit: `cover`,  
  margin: `0px`,  
});
  
const EllenCho: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `700`,  
  fontSize: `16px`,  
  letterSpacing: `0.64px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  flexGrow: `1`,  
  margin: `0px 0px 0px 8px`,  
});
 
function Sidebar2(props: Sidebar2Props): JSX.Element {
  
  const {data} = useSidebar2();
  return (
    <CollapsableOpen  className={props.className}   >
      <Top data={data} >
        <Logo data={data} >
          {(!(data.algo=1)) &&
            <MoonbaseLogo  src={`assets/images/Sidebar2_MoonbaseLogo.png`} alt={"MoonbaseLogo"}/>
          }
          {((data.algo=1)) &&
            <MoonbaseLogoM  src={`assets/images/Sidebar2_MoonbaseLogo_M.png`} alt={"MoonbaseLogo_M"}/>
          }
        </Logo>
        <List data={data} >
          <SidebarRow21   />
          <SidebarRow22   />
          <SidebarRow23   />
          <SidebarRow24   />
          <SidebarRow25   />
          <SidebarRow26   />
          <SidebarRow27   />
          <SidebarRow28   />
        </List>
      </Top>
      <Account data={data} >
        <Frame1 data={data} >
          <Avatar1  src={`assets/images/Sidebar2_Avatar.png`} alt={"Avatar"}/>
          {(!(data.algo=1)) &&
            <EllenCho >
              {`Ellen Cho`}
                </EllenCho>
          }
        </Frame1>
      </Account>
    </CollapsableOpen>
  );
}

export default Sidebar2;
