/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import MovieNavbar from 'components/MovieNavbar/MovieNavbar';
import BuyTicketBtn from 'components/BuyTicketBtn/BuyTicketBtn';
import SlideshowProgress from 'components/SlideshowProgress/SlideshowProgress';
import HpMovieThumbnail from 'components/HpMovieThumbnail/HpMovieThumbnail';
import SecondaryBtn from 'components/SecondaryBtn/SecondaryBtn';
import MovieFooter from 'components/MovieFooter/MovieFooter';
import { MovieHomePageTestOnlyProps } from 'types';

 
const ScreenMobile: any = styled("div")(({ theme }: any) =>({  
  backgroundColor: theme.palette["Background"]["Default"],  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  width: "100%",  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  overflow: `hidden`,  
  height: `4935.57px`,  
}));
  
const MovieNavbar1: any = styled(MovieNavbar)(({ theme }: any) =>({  
  alignSelf: `stretch`,  
  margin: `0px`,  
}));
  
const TopAndMask: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
  width: `375px`,  
});
  
const Top: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
  width: `375px`,  
});
  
const MovieImage: any = styled("div")({  
  backgroundImage: `url(assets/images/MovieHomePageTESTONLY_movie_image.png)`,  
  backgroundPosition: `center`,  
  backgroundSize: `cover`,  
  backgroundRepeat: `no-repeat`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `flex-end`,  
  padding: `10px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  height: `456px`,  
  margin: `0px`,  
  width: `375px`,  
});
  
const TitleDarkened: any = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `375px`,  
  height: `456px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const TitleMask: any = styled("div")({  
  background: `linear-gradient(39.69deg, rgba(0, 0, 0, 1) 1.244188344165035%, rgba(0, 0, 0, 0) 47.14643601850167%)`,  
  height: `402px`,  
  width: `638px`,  
  margin: `0px`,  
});
  
const TitleAndBuy: any = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-end`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `254px`,  
  left: `27px`,  
  top: `98px`,  
});
  
const MovieTitle: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Roboto`,  
  fontWeight: `900`,  
  fontSize: `32px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Description: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Roboto`,  
  fontWeight: `400`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `24px 0px 0px 0px`,  
});
  
const BuyTicketBtn1: any = styled(BuyTicketBtn)(({ theme }: any) =>({  
  margin: `24px 0px 0px 0px`,  
}));
  
const SlideshowProgress1: any = styled(SlideshowProgress)(({ theme }: any) =>({  
  margin: `0px`,  
}));
  
const ContentAndMask: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-end`,  
  alignItems: `center`,  
  padding: `40px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
  width: `375px`,  
});
  
const SecNowPlaying: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `30px 24px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
  width: `375px`,  
});
  
const CardInfo: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
  width: `327px`,  
});
  
const Movies: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
  width: `327px`,  
});
  
const NowPlaying: any = styled("div")(({ theme }: any) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: theme.palette["Text"]["Primary"],  
  fontStyle: `normal`,  
  fontFamily: `Roboto`,  
  fontWeight: `900`,  
  fontSize: `22px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
}));
  
const Thumbnails: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 0px 20px 0px`,  
  boxSizing: `border-box`,  
  margin: `14px 0px 0px 0px`,  
  width: `318px`,  
});
  
const HpMovieThumbnail1: any = styled(HpMovieThumbnail)(({ theme }: any) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px`,  
}));
  
const HpMovieThumbnail2: any = styled(HpMovieThumbnail)(({ theme }: any) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px 0px 0px 18px`,  
}));
  
const HpMovieThumbnail3: any = styled(HpMovieThumbnail)(({ theme }: any) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px 0px 0px 18px`,  
}));
  
const HpMovieThumbnail4: any = styled(HpMovieThumbnail)(({ theme }: any) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px 0px 0px 18px`,  
}));
  
const HpMovieThumbnail5: any = styled(HpMovieThumbnail)(({ theme }: any) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px 0px 0px 18px`,  
}));
  
const HpMovieThumbnail6: any = styled(HpMovieThumbnail)(({ theme }: any) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px 0px 0px 18px`,  
}));
  
const HpMovieThumbnail7: any = styled(HpMovieThumbnail)(({ theme }: any) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px 0px 0px 18px`,  
}));
  
const Thumbnails1: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 0px 20px 0px`,  
  boxSizing: `border-box`,  
  margin: `14px 0px 0px 0px`,  
  width: `318px`,  
});
  
const HpMovieThumbnail8: any = styled(HpMovieThumbnail)(({ theme }: any) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px`,  
}));
  
const HpMovieThumbnail9: any = styled(HpMovieThumbnail)(({ theme }: any) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px 0px 0px 18px`,  
}));
  
const Thumbnails2: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 0px 20px 0px`,  
  boxSizing: `border-box`,  
  margin: `14px 0px 0px 0px`,  
  width: `318px`,  
});
  
const HpMovieThumbnail10: any = styled(HpMovieThumbnail)(({ theme }: any) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px`,  
}));
  
const HpMovieThumbnail11: any = styled(HpMovieThumbnail)(({ theme }: any) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px 0px 0px 18px`,  
}));
  
const SecPromos: any = styled("div")({  
  backgroundColor: `rgba(23, 23, 23, 1)`,  
  borderRadius: `16px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 24px 60px 24px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `40px 0px 0px 0px`,  
  overflow: `hidden`,  
  width: `375px`,  
});
  
const Promo1: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `30px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
  width: `327px`,  
});
  
const PromoImgCropped: any = styled("div")({  
  backgroundImage: `url(assets/images/MovieHomePageTESTONLY_promo_img_cropped.png)`,  
  backgroundPosition: `center`,  
  backgroundSize: `cover`,  
  backgroundRepeat: `no-repeat`,  
  borderRadius: `10px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  alignSelf: `stretch`,  
  height: `300px`,  
  margin: `0px`,  
  overflow: `hidden`,  
  width: `327px`,  
});
  
const PromoInfo: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `40px 0px 0px 0px`,  
  width: `327px`,  
});
  
const Txt: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
  width: `327px`,  
});
  
const GetItPoppinAtHomeOrO: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Roboto`,  
  fontWeight: `600`,  
  fontSize: `22px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Description1: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 0.8)`,  
  fontStyle: `normal`,  
  fontFamily: `Roboto`,  
  fontWeight: `400`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `10px 0px 0px 0px`,  
});
  
const SecondaryBtn1: any = styled(SecondaryBtn)(({ theme }: any) =>({  
  margin: `18px 0px 0px 0px`,  
}));
  
const Promo2: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `30px 10px 30px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `20px 0px 0px 0px`,  
  width: `327px`,  
});
  
const CardImageCropped: any = styled("div")({  
  backgroundImage: `url(assets/images/MovieHomePageTESTONLY_card_image_cropped.png)`,  
  backgroundPosition: `center`,  
  backgroundSize: `cover`,  
  backgroundRepeat: `no-repeat`,  
  borderRadius: `10px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  alignSelf: `stretch`,  
  height: `300px`,  
  margin: `0px`,  
  overflow: `hidden`,  
  width: `317px`,  
});
  
const CardInfo1: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `40px 0px 0px 0px`,  
  width: `317px`,  
});
  
const Txt1: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
  width: `317px`,  
});
  
const ApplyForAPrePaidCard: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Roboto`,  
  fontWeight: `600`,  
  fontSize: `22px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Description2: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 0.8)`,  
  fontStyle: `normal`,  
  fontFamily: `Roboto`,  
  fontWeight: `400`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `10px 0px 0px 0px`,  
});
  
const BuyTicketBtn2: any = styled(BuyTicketBtn)(({ theme }: any) =>({  
  margin: `18px 0px 0px 0px`,  
}));
  
const SecComingSoon: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `30px 24px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `40px 0px 0px 0px`,  
  width: `375px`,  
});
  
const CardInfo2: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
  width: `327px`,  
});
  
const Movies1: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
  width: `327px`,  
});
  
const ComingSoon: any = styled("div")(({ theme }: any) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: theme.palette["Text"]["Primary"],  
  fontStyle: `normal`,  
  fontFamily: `Roboto`,  
  fontWeight: `900`,  
  fontSize: `22px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
}));
  
const Thumbnails3: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 0px 20px 0px`,  
  boxSizing: `border-box`,  
  margin: `10px 0px 0px 0px`,  
  width: `318px`,  
});
  
const HpMovieThumbnail12: any = styled(HpMovieThumbnail)(({ theme }: any) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px`,  
}));
  
const HpMovieThumbnail13: any = styled(HpMovieThumbnail)(({ theme }: any) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px 0px 0px 18px`,  
}));
  
const HpMovieThumbnail14: any = styled(HpMovieThumbnail)(({ theme }: any) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px 0px 0px 18px`,  
}));
  
const HpMovieThumbnail15: any = styled(HpMovieThumbnail)(({ theme }: any) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px 0px 0px 18px`,  
}));
  
const HpMovieThumbnail16: any = styled(HpMovieThumbnail)(({ theme }: any) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px 0px 0px 18px`,  
}));
  
const HpMovieThumbnail17: any = styled(HpMovieThumbnail)(({ theme }: any) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px 0px 0px 18px`,  
}));
  
const HpMovieThumbnail18: any = styled(HpMovieThumbnail)(({ theme }: any) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px 0px 0px 18px`,  
}));
  
const Thumbnails4: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 0px 20px 0px`,  
  boxSizing: `border-box`,  
  margin: `10px 0px 0px 0px`,  
  width: `318px`,  
});
  
const HpMovieThumbnail19: any = styled(HpMovieThumbnail)(({ theme }: any) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px`,  
}));
  
const HpMovieThumbnail20: any = styled(HpMovieThumbnail)(({ theme }: any) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px 0px 0px 18px`,  
}));
  
const Thumbnails5: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 0px 20px 0px`,  
  boxSizing: `border-box`,  
  margin: `10px 0px 0px 0px`,  
  width: `318px`,  
});
  
const HpMovieThumbnail21: any = styled(HpMovieThumbnail)(({ theme }: any) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px`,  
}));
  
const HpMovieThumbnail22: any = styled(HpMovieThumbnail)(({ theme }: any) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px 0px 0px 18px`,  
}));
  
const MovieFooter1: any = styled(MovieFooter)(({ theme }: any) =>({  
  alignSelf: `stretch`,  
  margin: `0px`,  
}));
 
function MovieHomePageTestOnly(props: MovieHomePageTestOnlyProps): JSX.Element {
  
  return (
    <ScreenMobile  className={props.className}   >
      <MovieNavbar1   />
      <TopAndMask >
        <Top >
          <MovieImage >
            <TitleDarkened >
              <TitleMask >
              </TitleMask>
            </TitleDarkened>
            <TitleAndBuy >
              <MovieTitle >
                {`Hero Movie catchy description to drive CTA button`}
                  </MovieTitle>
              <Description >
                {`Catchy description to drive CTA button lorem ipsum not to be read but just to fill space and exists as a placeholder to get a feel for content.`}
                  </Description>
              <BuyTicketBtn1   />
            </TitleAndBuy>
            <SlideshowProgress1   />
          </MovieImage>
        </Top>
        <ContentAndMask >
          <SecNowPlaying >
            <CardInfo >
              <Movies >
                <NowPlaying >
                  {`Now Playing`}
                    </NowPlaying>
                <Thumbnails >
                  <HpMovieThumbnail1   />
                  <HpMovieThumbnail2   />
                  {false &&
                    <HpMovieThumbnail3   />
                  }
                  {false &&
                    <HpMovieThumbnail4   />
                  }
                  {false &&
                    <HpMovieThumbnail5   />
                  }
                  {false &&
                    <HpMovieThumbnail6   />
                  }
                  {false &&
                    <HpMovieThumbnail7   />
                  }
                </Thumbnails>
                <Thumbnails1 >
                  <HpMovieThumbnail8   />
                  <HpMovieThumbnail9   />
                </Thumbnails1>
                <Thumbnails2 >
                  <HpMovieThumbnail10   />
                  <HpMovieThumbnail11   />
                </Thumbnails2>
              </Movies>
            </CardInfo>
          </SecNowPlaying>
          <SecPromos >
            <Promo1 >
              <PromoImgCropped >
              </PromoImgCropped>
              <PromoInfo >
                <Txt >
                  <GetItPoppinAtHomeOrO >
                    {`Get It Poppin’ at Home or on the Go`}
                      </GetItPoppinAtHomeOrO>
                  <Description1 >
                    {`Get that classic Nuvu theater popcorn taste at home. Packaged for carryout, so you can enjoy at game nights, parties, relaxing on the couch, and more.`}
                      </Description1>
                </Txt>
                <SecondaryBtn1   />
              </PromoInfo>
            </Promo1>
            <Promo2 >
              <CardImageCropped >
              </CardImageCropped>
              <CardInfo1 >
                <Txt1 >
                  <ApplyForAPrePaidCard >
                    {`Apply for a pre-paid card and get discounts and benefits`}
                      </ApplyForAPrePaidCard>
                  <Description2 >
                    {`Catchy description to drive CTA button lorem ipsum not to be read but just to fill space and exists as a placeholder to get a feel for content.`}
                      </Description2>
                </Txt1>
                <BuyTicketBtn2   />
              </CardInfo1>
            </Promo2>
          </SecPromos>
          <SecComingSoon >
            <CardInfo2 >
              <Movies1 >
                <ComingSoon >
                  {`Coming Soon`}
                    </ComingSoon>
                <Thumbnails3 >
                  <HpMovieThumbnail12   />
                  <HpMovieThumbnail13   />
                  {false &&
                    <HpMovieThumbnail14   />
                  }
                  {false &&
                    <HpMovieThumbnail15   />
                  }
                  {false &&
                    <HpMovieThumbnail16   />
                  }
                  {false &&
                    <HpMovieThumbnail17   />
                  }
                  {false &&
                    <HpMovieThumbnail18   />
                  }
                </Thumbnails3>
                <Thumbnails4 >
                  <HpMovieThumbnail19   />
                  <HpMovieThumbnail20   />
                </Thumbnails4>
                <Thumbnails5 >
                  <HpMovieThumbnail21   />
                  <HpMovieThumbnail22   />
                </Thumbnails5>
              </Movies1>
            </CardInfo2>
          </SecComingSoon>
        </ContentAndMask>
      </TopAndMask>
      <MovieFooter1   />
    </ScreenMobile>
  );
}

export default MovieHomePageTestOnly;
