/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import Frame1 from 'components/Frame1/Frame1';
import { Frame4Props } from 'types';

 
const Frame41: any = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  width: "100%",  
  height: `538px`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  overflow: `hidden`,  
});
  
const Frame2: any = styled(Frame1)(({ theme }: any) =>({  
  width: `1179px`,  
  height: `1373px`,  
  position: `absolute`,  
  left: `-30px`,  
  top: `-351px`,  
}));
 
function Frame4(props: Frame4Props): JSX.Element {
  
  return (
    <Frame41  className={props.className}   >
      <Frame2   />
    </Frame41>
  );
}

export default Frame4;
